/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function algorithmCreate(dto: AlgorithmCreateDto): Promise<AlgorithmDto>

/** 新增算法（不含 id） */
export interface AlgorithmCreateDto {
  name: string
  code: string
  desc?: string
  sort: number
}

export declare function algorithmDelete(id: number): Promise<boolean>

/** 算法列表 / 详情返回 */
export interface AlgorithmDto {
  id?: number
  name: string
  code: string
  desc?: string
  sort: number
}

export declare function algorithmGetAll(): Promise<Array<AlgorithmDto>>

export declare function algorithmGetById(id: number): Promise<AlgorithmDto | null>

export declare function algorithmGetPage(page: number, pageSize: number, keyword?: string | undefined | null): Promise<PageResultAlgorithmDto>

export declare function algorithmUpdate(dto: AlgorithmUpdateDto): Promise<AlgorithmDto>

/** 更新算法（必须带 id） */
export interface AlgorithmUpdateDto {
  id: number
  name: string
  code: string
  desc?: string
  sort: number
}

export declare function initDb(databaseUrl: string): Promise<void>

/** 图元 / 平台关联中的 `base_type` 字段，与数据库小写字符串一致 */
export declare const enum NodeBaseType {
  System = 'System',
  Custom = 'Custom'
}

export interface PageResultAlgorithmDto {
  list: Array<AlgorithmDto>
  total: number
}
